CREATE TABLE IF NOT EXISTS Person (
    person_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    year_of_birth INT CHECK (year_of_birth > 1900)
);

CREATE TABLE IF NOT EXISTS Book (
    book_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id INT REFERENCES Person(person_id) ON DELETE SET NULL,
    title VARCHAR(100) NOT NULL,
    author VARCHAR(100) NOT NULL DEFAULT 'Unknown author',
    year_of_publication INT CHECK (year_of_publication >= 0)
);